import Navbar from "@/components/Navbar";
import { spaceMono, workSans } from "./font";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} ${workSans.variable} font-workSans`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
