import { spaceMono, workSans } from "./font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.variable} ${workSans.variable} font-spaceMono`}>
        {children}
      </body>
    </html>
  );
}
